# Generated by Django 5.0.3 on 2024-03-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('titular', models.CharField(max_length=255)),
                ('duedate', models.DateField()),
                ('number', models.IntegerField()),
                ('type', models.CharField(max_length=2)),
                ('sucursal', models.CharField(max_length=255)),
            ],
        ),
    ]
