# Generated by Django 5.0.3 on 2024-04-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microserves', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Method',
        ),
    ]
